### ISSUE TITLE
Connection issue on port 41321

### ISSUE THREAD

**Issue by kulbinderdio** [purton-tech/fine-tuna#3]
Running docker compose up on Ubuntu, tried to upload a single line text file and got the following

fine-tuna-barricade-1     | [2023-09-07T10:49:23Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 204.650µs
fine-tuna-barricade-1     | [2023-09-07T10:49:23Z INFO  sqlx::query] SELECT id, user_id, session_verifier, …; rows affected: 0, rows returned: 1, elapsed: 222.934µs
fine-tuna-barricade-1     |     
fine-tuna-barricade-1     |     SELECT
fine-tuna-barricade-1     |       id,
fine-tuna-barricade-1     |       user_id,
fine-tuna-barricade-1     |       session_verifier,
fine-tuna-barricade-1     |       otp_code_confirmed,
fine-tuna-barricade-1     |       otp_code_encrypted,
fine-tuna-barricade-1     |       otp_code_attempts,
fine-tuna-barricade-1     |       otp_code_sent
fine-tuna-barricade-1     |     FROM
fine-tuna-barricade-1     |       sessions
fine-tuna-barricade-1     |     WHERE
fine-tuna-barricade-1     |       id = $1
fine-tuna-barricade-1     |     
fine-tuna-barricade-1     | [2023-09-07T10:49:23Z INFO  actix_web::middleware::logger] 172.19.0.2 "POST /app/team/1/dataset/1/doc_upload HTTP/1.1" 200 0 "-" "-" 0.000727
fine-tuna-barricade-1     | [2023-09-07T10:49:23Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 151.458µs
fine-tuna-app-1           | 2023-09-07T10:49:23.519647Z  INFO axum_server::documents::upload_doc: Sending document to unstructured
fine-tuna-unstructured-1  | 2023-09-07 10:49:23,522 unstructured_api DEBUG pipeline_api input params: {"request": "<starlette.requests.Request object at 0x7f3d901e1400>", "filename": "test1.txt", "file_content_type": "text/plain", "response_type": "application/json", "m_coordinates": [], "m_encoding": [], "m_hi_res_model_name": [], "m_include_page_breaks": [], "m_ocr_languages": [], "m_pdf_infer_table_structure": [], "m_skip_infer_table_types": [], "m_strategy": [], "m_xml_keep_tags": []}
fine-tuna-unstructured-1  | 2023-09-07 10:49:23,522 unstructured_api DEBUG partition input data: {"content_type": "text/plain", "strategy": "auto", "ocr_languages": "eng", "coordinates": false, "pdf_infer_table_structure": false, "include_page_breaks": false, "encoding": null, "model_name": null, "xml_keep_tags": false, "skip_infer_table_types": ["pdf", "jpg", "png"]}
fine-tuna-unstructured-1  | 2023-09-07 10:49:23,524 172.19.0.6:48718 POST /general/v0/general HTTP/1.1 - 200 OK
fine-tuna-app-1           | 2023-09-07T10:49:23.525172Z  INFO axum_server::documents::upload_doc: Generating embeddings
fine-tuna-llm-api-1       | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:41321: connect: connection refused"

Can't see any container listening on this port

**Comment by kulbinderdio** [comment]
output from docker ps

CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                    PORTS                                                  NAMES
ecc7771c060d   ghcr.io/purton-tech/fine-tuna:1.4.6               "./axum-server"          14 minutes ago   Up 14 minutes                                                                    fine-tuna-app-1
171698af972b   purtontech/barricade                              "./barricade"            14 minutes ago   Up 14 minutes                                                                    fine-tuna-barricade-1
70e4b99ad1d7   ankane/pgvector                                   "docker-entrypoint.s…"   14 minutes ago   Up 14 minutes (healthy)   5432/tcp                                               fine-tuna-db-1
02e0db9abf7a   quay.io/unstructured-io/unstructured-api:0.0.34   "scripts/app-start.sh"   14 minutes ago   Up 14 minutes             0.0.0.0:8000->8000/tcp, :::8000->8000/tcp              fine-tuna-unstructured-1
65a1efac0ff0   ghcr.io/purton-tech/fine-tuna-model-api:latest    "/build/entrypoint.sh"   14 minutes ago   Up 14 minutes (healthy)   8080/tcp                                               fine-tuna-llm-api-1
3261f45a5be7   ghcr.io/purton-tech/fine-tuna-envoy:1.4.6         "/docker-entrypoint.…"   14 minutes ago   Up 14 minutes             10000/tcp, 0.0.0.0:7800->7700/tcp, :::7800->7700/tcp   fine-tuna-envoy-1
792103e19061   portainer/agent:latest                            "./agent"                6 months ago     Up About an hour          0.0.0.0:9001->9001/tcp, :::9001->9001/tcp              portainer_agent

**Comment by kulbinderdio** [comment]
Just tried same on MacMini (intel) setup and got similar, but different port number

fine-tuna-barricade-1     | [2023-09-07T10:53:18Z INFO  actix_web::middleware::logger] 172.18.0.2 "POST /app/team/1/dataset/1/doc_upload HTTP/1.1" 200 0 "-" "-" 0.001626
fine-tuna-barricade-1     | [2023-09-07T10:53:18Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 662.009µs
fine-tuna-app-1           | 2023-09-07T10:53:18.132295Z  INFO axum_server::documents::upload_doc: Sending document to unstructured
fine-tuna-unstructured-1  | 2023-09-07 10:53:18,174 unstructured_api DEBUG pipeline_api input params: {"request": "<starlette.requests.Request object at 0x7f348f40b160>", "filename": "test2.txt", "file_content_type": "text/plain", "response_type": "application/json", "m_coordinates": [], "m_encoding": [], "m_hi_res_model_name": [], "m_include_page_breaks": [], "m_ocr_languages": [], "m_pdf_infer_table_structure": [], "m_skip_infer_table_types": [], "m_strategy": [], "m_xml_keep_tags": []}
fine-tuna-unstructured-1  | 2023-09-07 10:53:18,174 unstructured_api DEBUG partition input data: {"content_type": "text/plain", "strategy": "auto", "ocr_languages": "eng", "coordinates": false, "pdf_infer_table_structure": false, "include_page_breaks": false, "encoding": null, "model_name": null, "xml_keep_tags": false, "skip_infer_table_types": ["pdf", "jpg", "png"]}
fine-tuna-unstructured-1  | 2023-09-07 10:53:18,636 172.18.0.7:50854 POST /general/v0/general HTTP/1.1 - 200 OK
fine-tuna-app-1           | 2023-09-07T10:53:18.649644Z  INFO axum_server::documents::upload_doc: Generating embeddings
fine-tuna-llm-api-1       | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:36409: connect: connection refused"
fine-tuna-db-1            | 2023-09-07 10:53:21.726 UTC [27] LOG:  checkpoint starting: time
fine-tuna-db-1            | 2023-09-07 10:53:24.578 UTC [27] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.520 s, sync=0.772 s, total=2.852 s; sync files=7, longest=0.762 s, average=0.111 s; distance=21 kB, estimate=21 kB

**Comment by kulbinderdio** [comment]
output from docker ps

CONTAINER ID   IMAGE                                             COMMAND                  CREATED        STATUS                   PORTS                               NAMES
7b5457eeb97e   ghcr.io/purton-tech/fine-tuna:1.4.6               "./axum-server"          21 hours ago   Up 6 minutes                                                 fine-tuna-app-1
4c00a4a9465b   purtontech/barricade                              "./barricade"            21 hours ago   Up 6 minutes                                                 fine-tuna-barricade-1
c834978ccf8c   ghcr.io/purton-tech/fine-tuna-envoy:1.4.6         "/docker-entrypoint.…"   21 hours ago   Up 6 minutes             10000/tcp, 0.0.0.0:7800->7700/tcp   fine-tuna-envoy-1
6ea96e4eb23c   ankane/pgvector                                   "docker-entrypoint.s…"   21 hours ago   Up 6 minutes (healthy)   5432/tcp                            fine-tuna-db-1
c5f89b20c5b5   ghcr.io/purton-tech/fine-tuna-model-api:latest    "/build/entrypoint.sh"   21 hours ago   Up 6 minutes (healthy)   8080/tcp                            fine-tuna-llm-api-1
19620e41de8d   quay.io/unstructured-io/unstructured-api:0.0.34   "scripts/app-start.sh"   21 hours ago   Up 6 minutes             0.0.0.0:8000->8000/tcp              fine-tuna-unstructured-1
dio@mac-mini fine-tuna % 

going to take down and delete volumes and try again

**Comment by kulbinderdio** [comment]
now getting

fine-tuna-barricade-1     |     
fine-tuna-barricade-1     | [2023-09-07T11:01:05Z INFO  actix_web::middleware::logger] 172.18.0.4 "POST /app/team/1/dataset/1/doc_upload HTTP/1.1" 200 0 "-" "-" 0.001219
fine-tuna-barricade-1     | [2023-09-07T11:01:05Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 393.075µs
fine-tuna-app-1           | 2023-09-07T11:01:05.763484Z  INFO axum_server::documents::upload_doc: Sending document to unstructured
fine-tuna-unstructured-1  | 2023-09-07 11:01:06,621 unstructured_api DEBUG pipeline_api input params: {"request": "<starlette.requests.Request object at 0x7f739461d190>", "filename": "test.txt", "file_content_type": "text/plain", "response_type": "application/json", "m_coordinates": [], "m_encoding": [], "m_hi_res_model_name": [], "m_include_page_breaks": [], "m_ocr_languages": [], "m_pdf_infer_table_structure": [], "m_skip_infer_table_types": [], "m_strategy": [], "m_xml_keep_tags": []}
fine-tuna-unstructured-1  | 2023-09-07 11:01:06,621 unstructured_api DEBUG partition input data: {"content_type": "text/plain", "strategy": "auto", "ocr_languages": "eng", "coordinates": false, "pdf_infer_table_structure": false, "include_page_breaks": false, "encoding": null, "model_name": null, "xml_keep_tags": false, "skip_infer_table_types": ["pdf", "jpg", "png"]}
fine-tuna-unstructured-1  | 2023-09-07 11:01:08,094 172.18.0.8:36442 POST /general/v0/general HTTP/1.1 - 200 OK
fine-tuna-app-1           | 2023-09-07T11:01:08.095924Z  INFO axum_server::documents::upload_doc: Generating embeddings
fine-tuna-llm-api-1       | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:39509: connect: connection refused"
fine-tuna-llm-api-1       | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:39509: connect: connection refused"
fine-tuna-llm-api-1       | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:39509: connect: connection refused"
fine-tuna-llm-api-1       | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:39509: connect: connection refused"

**Comment by ianpurton** [comment]
@kulbinderdio I also get that error but then it continues to process. It might be a red herring.

Can you attach the file?

**Comment by kulbinderdio** [comment]
File doesn't attach, only managed to upload one 1 line txt file, all others have been unsuccessful, without any other error showing

**Comment by kulbinderdio** [comment]
this is the output every time

fine-tuna-barricade-1     | [2023-09-07T12:39:16Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 200.653µs
fine-tuna-barricade-1     | [2023-09-07T12:39:16Z INFO  sqlx::query] SELECT id, user_id, session_verifier, …; rows affected: 0, rows returned: 1, elapsed: 302.444µs
fine-tuna-barricade-1     |     
fine-tuna-barricade-1     |     SELECT
fine-tuna-barricade-1     |       id,
fine-tuna-barricade-1     |       user_id,
fine-tuna-barricade-1     |       session_verifier,
fine-tuna-barricade-1     |       otp_code_confirmed,
fine-tuna-barricade-1     |       otp_code_encrypted,
fine-tuna-barricade-1     |       otp_code_attempts,
fine-tuna-barricade-1     |       otp_code_sent
fine-tuna-barricade-1     |     FROM
fine-tuna-barricade-1     |       sessions
fine-tuna-barricade-1     |     WHERE
fine-tuna-barricade-1     |       id = $1
fine-tuna-barricade-1     |     
fine-tuna-barricade-1     | [2023-09-07T12:39:16Z INFO  actix_web::middleware::logger] 172.19.0.2 "POST /app/team/1/dataset/1/doc_upload HTTP/1.1" 200 0 "-" "-" 0.000802
fine-tuna-barricade-1     | [2023-09-07T12:39:16Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 152.881µs
fine-tuna-app-1           | 2023-09-07T12:39:16.226806Z  INFO axum_server::documents::upload_doc: Sending document to unstructured
fine-tuna-unstructured-1  | 2023-09-07 12:39:16,229 unstructured_api DEBUG pipeline_api input params: {"request": "<starlette.requests.Request object at 0x7f3d8e194ca0>", "filename": "test2.txt", "file_content_type": "text/plain", "response_type": "application/json", "m_coordinates": [], "m_encoding": [], "m_hi_res_model_name": [], "m_include_page_breaks": [], "m_ocr_languages": [], "m_pdf_infer_table_structure": [], "m_skip_infer_table_types": [], "m_strategy": [], "m_xml_keep_tags": []}
fine-tuna-unstructured-1  | 2023-09-07 12:39:16,229 unstructured_api DEBUG partition input data: {"content_type": "text/plain", "strategy": "auto", "ocr_languages": "eng", "coordinates": false, "pdf_infer_table_structure": false, "include_page_breaks": false, "encoding": null, "model_name": null, "xml_keep_tags": false, "skip_infer_table_types": ["pdf", "jpg", "png"]}
fine-tuna-unstructured-1  | 2023-09-07 12:39:16,231 172.19.0.6:48718 POST /general/v0/general HTTP/1.1 - 200 OK
fine-tuna-app-1           | 2023-09-07T12:39:16.232037Z  INFO axum_server::documents::upload_doc: Generating embeddings
fine-tuna-llm-api-1       | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:36789: connect: connection refused"

**Comment by ianpurton** [comment]
This might be an issue with localai running in docker on an intel mac. It will be running virtualised.

I'll put together a way to test it.

**Comment by kulbinderdio** [comment]
this is the output when upload button returns very quickly and document has not been uploaded

fine-tuna-barricade-1     | [2023-09-07T12:46:29Z WARN  sqlx::postgres::notice] terminating connection because of crash of another server process
fine-tuna-barricade-1     | [2023-09-07T12:46:29Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 10.533ms
fine-tuna-barricade-1     | [2023-09-07T12:46:29Z INFO  sqlx_core::pool::inner] ping on idle connection returned error: error communicating with database: connection aborted
fine-tuna-barricade-1     | [2023-09-07T12:46:29Z INFO  sqlx::query] SELECT id, user_id, session_verifier, …; rows affected: 0, rows returned: 1, elapsed: 111.498ms
fine-tuna-barricade-1     |     
fine-tuna-barricade-1     |     SELECT
fine-tuna-barricade-1     |       id,
fine-tuna-barricade-1     |       user_id,
fine-tuna-barricade-1     |       session_verifier,
fine-tuna-barricade-1     |       otp_code_confirmed,
fine-tuna-barricade-1     |       otp_code_encrypted,
fine-tuna-barricade-1     |       otp_code_attempts,
fine-tuna-barricade-1     |       otp_code_sent
fine-tuna-barricade-1     |     FROM
fine-tuna-barricade-1     |       sessions
fine-tuna-barricade-1     |     WHERE
fine-tuna-barricade-1     |       id = $1
fine-tuna-barricade-1     |     
fine-tuna-barricade-1     | [2023-09-07T12:46:29Z INFO  actix_web::middleware::logger] 172.18.0.4 "POST /app/team/1/dataset/1/doc_upload HTTP/1.1" 200 0 "-" "-" 0.260728
fine-tuna-barricade-1     | [2023-09-07T12:46:29Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 524.150µs

**Comment by kulbinderdio** [comment]
Wondering if its an issue with low spec machines. I have now managed to uploaded very small docs only twice.
Is there any further debugging I can turn on?

**Comment by kulbinderdio** [comment]
> This might be an issue with localai running in docker on an intel mac. It will be running virtualised.
> 
> I'll put together a way to test it.

I get the same/similar when running on ubuntu (that is installed on MacMini)

**Comment by ianpurton** [comment]
How much ram do you have?

**Comment by kulbinderdio** [comment]
16GB, but it's old processor, 2.8GHz dual core i5.

Maybe detail minimum hardware requirements
